# Generated by Django 2.0.13 on 2019-04-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_pick', '0002_auto_20190409_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='movie',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
